version: '3.9'
services:
  node-app:
    build:
      context: .
    container_name: nodeMongoApp
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - keploy-network  
  mongo:
    image: mongo
    container_name: mongoDb
    ports:
      - 27017:27017
    networks:
      - keploy-network

networks:
  keploy-network:
    external: true
